//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admin_SMTP_parametere
    {
        public int Ind { get; set; }
        public string UserName { get; set; }
        public string password { get; set; }
        public string host { get; set; }
    }
}
