//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Info
    {
        public int ID { get; set; }
        public Nullable<int> IDProvider { get; set; }
        public Nullable<int> IDEmployee { get; set; }
        public Nullable<int> IDDestinationProvider { get; set; }
        public Nullable<int> IDAccommodation { get; set; }
        public string AccommodationTypeName { get; set; }
        public string WebAddress { get; set; }
        public Nullable<int> Category { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Tel1 { get; set; }
        public string Tel2 { get; set; }
    
        public virtual Accommodation Accommodation { get; set; }
        public virtual CTEmployee CTEmployee { get; set; }
        public virtual Destination Destination { get; set; }
        public virtual Provider Provider { get; set; }
    }
}
