//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class LifeInCity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LifeInCity()
        {
            this.Feedbacks = new HashSet<Feedback>();
            this.Pictures = new HashSet<Picture>();
        }
    
        public int ID { get; set; }
        public int IDDestination { get; set; }
        public int IDAccTraDesCategory { get; set; }
        public string Description { get; set; }
        public System.DateTime ChangeDate { get; set; }
        public int IDAdmin { get; set; }
    
        public virtual AccTraDesCategory AccTraDesCategory { get; set; }
        public virtual CTEmployee CTEmployee { get; set; }
        public virtual Destination Destination { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Feedback> Feedbacks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Picture> Pictures { get; set; }
    }
}
