//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Picture
    {
        public int ID { get; set; }
        public Nullable<int> IDLifeInCity { get; set; }
        public Nullable<int> IDAccommodation { get; set; }
        public Nullable<int> IDEmployee { get; set; }
        public Nullable<int> IDProvider { get; set; }
    
        public virtual Accommodation Accommodation { get; set; }
        public virtual LifeInCity LifeInCity { get; set; }
        public virtual Provider Provider { get; set; }
    }
}
